### ISSUE TITLE
`fs.FromDir` can fail during copy

### ISSUE THREAD

**Issue by vdemeester** [gotestyourself/gotest.tools#103]
If the folder we want to *copy from* contains weird files like dead link, it can error out.
I feel we should make it possible to pass options to `FromDir` like `ignoreDeadLink` or something like that.

cc @dnephin wdyt ?

**Comment by dnephin** [comment]
Hmm, I agree it shouldn't error. I don't think we need options. It should copy links as links instead of trying to copy the link target. There's a `TODO: handle symlinks` in `copyDirectory` that needs to be implemented. I think that would fix this.
