### ISSUE TITLE
assert.Error failure message can be difficult to understand

### ISSUE THREAD

**Issue by silvin-lubecki** [gotestyourself/gotest.tools#109]
[This commit](https://github.com/gotestyourself/gotest.tools/commit/b7851db4d7a4f86767af507d5d3d69760c2baa5b#diff-a8838b41d14460575213392c5f6f6c5dL173) introduced a bug when printing an error wrapped using `github.com/pkg/errors`.
It can print the stacks embedded with the error, but won't print the full error message as it would using `%q` which calls err.Error().

For example here the case I had:

```
-- FAIL: TestValidateBrokenSettings (0.00s)
        validate_test.go:61: assertion failed: expected error "Non-string key in my-settings: 1", got Non-string key in my-settings: 1
                github.com/docker/app/internal/settings.formatInvalidKeyError
                        /go/src/github.com/docker/app/internal/settings/load.go:110
                github.com/docker/app/internal/settings.convertToStringKeysRecursive
```
I had `expected error "Non-string key in my-settings: 1", got Non-string key in my-settings: 1`, which is a little misleading 😅 . The real message was:
```
fmt.Printf("err := '%s'\n", err)
assert.Error(t, err, `Non-string key in my-settings: 1`)
```
```
err := 'failed to load settings: Non-string key in my-settings: 1'
--- FAIL: TestValidateBrokenSettings (0.00s)
        validate_test.go:63: assertion failed: expected error "Non-string key in my-settings: 1", got Non-string key in my-settings: 1
```
Maybe it would be good to print the two versions `%q\n%+v`? Or maybe add a special case for errors from `pkg/errors`?

**Comment by dnephin** [comment]
Fixed by #110
