### ISSUE TITLE
Better approach for asserting "any error"

### ISSUE THREAD

**Issue by thaJeztah** [gotestyourself/gotest.tools#154]
Perhaps it's just not best practice, but I found a fair share of tests asserting that "an error" is produced. For most of those tests it either doesn't really matter "what error" is produced, and for some, we can't rely on the exact error message (either because it's platform specific, changes between test-environments, or just difficult to re-construct the error-message for testing).

Basically; what would be the best approach to test if "an error", and would it make sense to add a dedicated utility for this? (e.g. `assert.AnyError(t, err)` or `assert.Check(t, cmp.AnyError(err))`)

```go
func TestAnyError(t *testing.T) {
	err := errors.New("Hello world")

	// This works, and might be the cleanest solution
	assert.Assert(t, err != nil)

	// This also works, but it's ugly;
	assert.ErrorContains(t, err, "")

	// ErrorType, well ...
	assert.ErrorType(t, err, errors.New(""))

	// Using `assert.Error` is the situation we're trying to avoid (as we either
	// don't know the actual error-string, or well, we don't  really care about the error-message
	// ("Error fails the test if err is nil, **or the error message is not the expected message.**)
	assert.Error(t, err, "Hello world")
}
```

@vdemeester @dnephin

**Comment by dnephin** [comment]
I think this one looks right:
```go
assert.Assert(t, err != nil)
```

I don't think we should add a separate utility for something like this because it's definitely not a best practice, and should be (hopefully) a rare occurrence. I think for many of the cases you describe I would expect the function I am testing to have wrapped the original error with some additional context, so any test I write could check for the additional context using `assert.ErrorContains()`.

**Comment by thaJeztah** [comment]
>  I think for many of the cases you describe I would expect the function I am testing to have wrapped the original error with some additional context, so any test I write could check for the additional context using assert.ErrorContains().

Ideally, yes; I ran into these when running tests against different combinations of docker client/daemon, where the error message would differ 🤷‍♂️ 

Anyway; thanks for having a look; let me close this one 🤗
