### ISSUE TITLE
TestDeepEqualFailure fails w/ go 1.12.2

### ISSUE THREAD

**Issue by eclipseo** [gotestyourself/gotest.tools#155]
gotest.tools 2.3.0 w/ Go 1.12.2 on Fedora Rawhide, x86_64:

```
Testing    in: /builddir/build/BUILD/gotest.tools-2.3.0/_build/src
         PATH: /builddir/build/BUILD/gotest.tools-2.3.0/_build/bin:/builddir/.local/bin:/builddir/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
       GOPATH: /builddir/build/BUILD/gotest.tools-2.3.0/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test -buildmode pie -compiler gc -ldflags "-X gotest.tools/version=2.3.0 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '"
      testing: gotest.tools
gotest.tools/assert
--- FAIL: TestDeepEqualFailure (0.00s)
    assert_test.go:305: should have failure message "assertion failed: \n--- actual\n+++ expected\n{assert.stub}.b:\n\t-: 1\n\t+: 2\n", got "assertion failed: \n--- actual\n+++ expected\n\u00a0\u00a0assert.stub{\n\u00a0\u00a0\ta: \"ok\",\n-\u00a0\tb: 1,\n+\u00a0\tb: 2,\n\u00a0\u00a0}\n"
FAIL
exit status 1
FAIL	gotest.tools/assert	0.028s
```

**Comment by dnephin** [comment]
I am not able to reproduce the problem. CI runs against the latest golang 1.12 image. You can see a run here: https://circleci.com/gh/gotestyourself/gotest.tools/1835#tests/containers/0

This ran with 1.12.4 and all the tests passed.

Maybe the extra flags you are passing (`-buildmode pie -compiler gc  ...`) change the expected error? I think the tests are run with cgo disabled.

**Comment by eclipseo** [comment]
Might be because I use go-cmp 0.3.0

**Comment by dnephin** [comment]
Oh, that sounds very likely. If I can reproduce the problem with go-cmp 0.3.0 I can fix the test to work with both. I'll give that a try sometime soon.

**Comment by dnephin** [comment]
You are correct that the change is go-cmp 0.3.0. I pushed a PR which attempts to fix the problem, but it's not pretty (and it's still failing some tests).

**Comment by anthonyfok** [comment]
It seems that the current  PR #158 does not yet fix this very issue, the reason being this failure appears randomly.  In go-cmp 0.3.0, the report randomly chooses between normal space (0x20) and non-breaking space (0xa0) in the report...  I just got bitten by this in Debian packaging, as one build succeeds and yet the next build fails even though I did not change anything.

I was very perplexed until I searched for `00a0` in go-cmp, and found it uses rand to choose between U+0020 and U+00a0 randomly.  Crazy, I'd say, but it follows the same spirit in Go where nothing is deterministic if the author doesn't want you to use it...  Sigh...
Please see https://github.com/google/go-cmp/pull/124 for the whole story.

**Comment by anthonyfok** [comment]
Sorry, my previous message was incomplete: The error that failed in my case is TestDeepEqual in assert/cmp/compare_test.go as it appears to be the only one doing go-cmp report string comparison.

Since this has nothing to do with TestDeepEqualFailure as stated in the issue title, Maybe I should move this discussion to #158 instead.  My apologies!
