### ISSUE TITLE
go modules compatibility

### ISSUE THREAD

**Issue by gracenoah** [gotestyourself/gotest.tools#156]
For compatibility with go modules, the import path in the go.mod file in this repo must have a /v2 suffix. Otherwise users of this library will get:
```
go: gotest.tools/v2@v2.3.0: go.mod has non-.../v2 module path "gotest.tools" (and .../v2/go.mod does not exist) at revision v2.3.0
```
The workaround is for users to add the following to their go.mod file:
```
// The import path for this version doesn't work with go.mod because the go.mod file is missing the version suffix
replace gotest.tools => gotest.tools v2.3.0
```

**Comment by dnephin** [comment]
Thanks for the report! I have had PR #140 sitting for a while, which should fix the issue. I should get around to merging that soon.

**Comment by mangatmodi** [comment]
+1
