### ISSUE TITLE
RFE: fs withReader

### ISSUE THREAD

**Issue by glenjamin** [gotestyourself/gotest.tools#160]
I found myself wanting to populate a temp file in a test with the results of an io.Reader.

I read that into a byte buffer and passed it along, but this could be something that comes up often enough to be worth adding into the DSL.

**Comment by dnephin** [comment]
`WithContentFromReader(io.Reader) PathOp` seems like a good addition to `gotest.tools/fs`.

It's almost possible to implement these PathOp outside the package. External ones work with the filesystem, but `manifestFile` is not exported, so it's not possible to implement one that works with manifests for expected values. Perhaps the package should also export `IsManfiestFile` or the `manifestFile` type to make that possible.

**Comment by icholy** [comment]
@dnephin This can be closed I think. Maybe another issue can be opened for allowing external PathOp implementations.
