### ISSUE TITLE
unable to compile tests due to "expects import"

### ISSUE THREAD

**Issue by mankinskin** [gotestyourself/gotest.tools#166]
I am not sure what happened, but the tests worked when I pushed them to our repository, now when I try to run `go test` I get these errors (changed directory names):
```
$ go test
# ~/git/repo
package ~/git/repo (test)
	imports gotest.tools/assert
	imports gotest.tools/v3/assert/cmp: code in directory ~/go/src/gotest.tools/assert/cmp expects import "gotest.tools/assert/cmp"
FAIL	~/git/repo [setup failed]
```
This is how I import gotest.tools:
```
import (
	"gotest.tools/assert"
	"net/http"
	"testing"
)
```

How does this happen all of a sudden? I tried reinstalling everything, even cleared my GOPATH completely, but the error remains.

**Comment by dnephin** [comment]
Which version of Go are you using? If you aren't using go1.11+ you may need to pin the version to v2.3.0. 

A v3 was released recently with full go module support, which changed the import path: https://github.com/gotestyourself/gotest.tools/pull/140

**Comment by mankinskin** [comment]
I am using go1.13.1. Is there an easy way how I can use the updated gotest.tools version?

**Comment by dnephin** [comment]
Yup, you can change your imports to `gotest.tools/v3/assert`. https://github.com/marwan-at-work/mod claims to be able to automate this, although I've had mixed success.

You could also use `git grep -l '"gotest.tools/" | xargs sed ..." if you are familiar with that.

**Comment by dnephin** [comment]
@mankinskin did you get this working with the new import path?

**Comment by mankinskin** [comment]
We switched to [testify/assert](https://github.com/stretchr/testify) for now unfortunately, until we made the transition to go modules. Actually we did this by now, and I just tried switching the import back to `github.com/gotestyourself/gotest.tools/assert`, ran `go get -u -v github.com/gotestyourself/gotest.tools` (no errors) but when I try `go test`, I get this error:
```
imports github.com/gotestyourself/gotest.tools/assert
imports gotest.tools/internal/format: use of internal package gotest.tools/internal/format not allowed
```

**Comment by dnephin** [comment]
I'll add some notes to the README to make this easier to find

**Comment by dnephin** [comment]
Added some text in #170

**Comment by saurabhsuniljain** [comment]
> 
> 
> Yup, you can change your imports to `gotest.tools/v3/assert`. https://github.com/marwan-at-work/mod claims to be able to automate this, although I've had mixed success.
> 
> You could also use `git grep -l '"gotest.tools/" | xargs sed ...` if you are familiar with that.

@dnephin This is not needed in the latest version right? I am still getting this error, 

```
package druva.com/baikal/localStream (test)
	imports gotest.tools/assert
	imports gotest.tools/v3/assert/cmp: code in directory /home/work/go/src/gotest.tools/assert/cmp expects import "gotest.tools/assert/cmp"
FAIL	druva.com/baikal/localStream [setup failed]

```

**Comment by dnephin** [comment]
I believe it is needed in all future versions, yes. `gotest.tools/assert` is only a valid import for the v3 version of the package, which is long out of date.

**Comment by dnephin** [comment]
Which version of Go are you using that reported that error?

**Comment by saurabhsuniljain** [comment]
I am using Go1.10

**Comment by NikTJ777** [comment]
I cannot make this work either way.

I am using Go 1.13.6.

If I use `import "gotest.tools/assert"
I get the error: `expects import "gotest.tools/v3/assert"`

If I use "import "gotest.tools/v3/assert"
I get the error: `cannot find package "gotest.tools/v3/assert"`

I originally pulled the packge with "go get gootest.tools"
If I try "go get gotest.tools/v3"
I get: `package gotest.tools/v3: cannot find package "gotest.tools/v3"`

Seems like a catch-22.
What can I do to avoid all the errors?

**Comment by dnephin** [comment]
Have you read the README? https://github.com/gotestyourself/gotest.tools#usage. It was linked from https://github.com/gotestyourself/gotest.tools/issues/166#issuecomment-552123029, committed in #170

> $ go get gotest.tools/v3

```
$ go version
go version go1.13.8 linux/amd64
$ mkdir newproj
$ cd newproj/
$ go mod init example.com/newproj
go: creating new go.mod: module example.com/newproj
$ go get gotest.tools/v3
```

**Comment by NikTJ777** [comment]
Yes, I had read the README.
Nowhere did it say to execute "go mod init ..."

However, from your set of commands above, I now understand the oblique:
"With Go modules enabled (go1.11+)"
to mean: "execute 'go mod init ..."

Thank you for your response - most helpful.
