### ISSUE TITLE
subtest's testcase.Cleanup conflicts with Go 1.14's new Cleanup

### ISSUE THREAD

**Issue by zikaeroh** [gotestyourself/gotest.tools#168]
golang/go#32111 adds a cleanup function to the standard lib's testing types. This breaks `x/subtest` at compile time, like:

```
# gotest.tools/v3/x/subtest
../../../nobackup/gotip_home/gopath/pkg/mod/gotest.tools/v3@v3.0.0/x/subtest/context.go:63:10: cannot use tc (type *testcase) as type TestContext in argument to subtest:
	*testcase does not implement TestContext (wrong type for Cleanup method)
		have Cleanup()
		want Cleanup(func())
../../../nobackup/gotip_home/gopath/pkg/mod/gotest.tools/v3@v3.0.0/x/subtest/context.go:81:5: cannot use &testcase literal (type *testcase) as type TestContext in assignment:
	*testcase does not implement TestContext (wrong type for Cleanup method)
		have Cleanup()
		want Cleanup(func())
```

As `testcase` defines a `Cleanup` function of its own, conflicting with `testing.TB`'s definition. This type is not exported, and `Cleanup` does not appear to be used externally, only in `x/subtest`. Can this function be unexported or renamed to allow for this package to compile at tip?

**Comment by dnephin** [comment]
Thanks for the report. I saw a similar report over in another repo where I got the inspiration for `x/subtest` and I forgot that I had done the same thing. I'll take a closer look at how they solved it and see if the same fix can be applied here.

Since `x/subtest` is experimental I think it would be ok to make a breaking change and have Cleanup take a `func()` (assuming that would fix the problem).

**Comment by zikaeroh** [comment]
This can be fixed without breaking compatibility at all, actually. `Cleanup` is an internal only function which actually calls the cleanup funcs, and would only be available if someone where to define an interface for  `Cleanup()` and then cast it. `AddCleanup` in `subtest` is the thing that's analogous to the new `Cleanup(func())`. I can send a PR, it's just a three character change.
