### ISSUE TITLE
Errors from Golden could provide a hint about updating

### ISSUE THREAD

**Issue by glenjamin** [gotestyourself/gotest.tools#172]
Passing `-test.update-golden` to update the golden files works well, but if you're not already familiar with the library, then it's not especially discoverable.

Could the assertion failure include some help text which tells the user that this flag exists?

**Comment by dnephin** [comment]
>  it's not especially discoverable

The docstring for the `Assert` function in the package (https://godoc.org/gotest.tools/golden#Assert) does mention the flag. Adding it to the package docstring would also be good.

`golden` is a cross-language testing pattern. [The first hit on google for golden testing](https://ro-che.info/articles/2017-12-04-golden-tests) mentions that "The expected output can be automatically updated.".

There are certainly ways to discover it. Adding it to the assertion error would make the errors somewhat verbose. I would rather avoid it.

**Comment by glenjamin** [comment]
I think adding to the package docstring would work, yeah.

I knew there was a way to auto-update, but as a consumer of a test someone else wrote, I would generally by looking at the assertion output to tell me what the problem was - not the docs of the assertion library.

The errors are already going to be fairly verbose, as they'll usually be multi-line string diffs.

**Comment by dnephin** [comment]
Maybe there is a way to include something in the failure message that suggests how to fix it without it being overly verbose.

**Comment by glenjamin** [comment]
Jest is the other tool that I know had good integration for golden testing, but their approach is _very_ fancy.

https://jestjs.io/docs/en/snapshot-testing#updating-snapshots

**Comment by dnephin** [comment]
Opened #175 for this

**Comment by glenjamin** [comment]
Looks good, thanks!
