### ISSUE TITLE
Typed nil errors should not pass "NilError"

### ISSUE THREAD

**Issue by zikaeroh** [gotestyourself/gotest.tools#185]
I don't think the fix for #167 (#171) was entirely correct. A typed `nil` error is not a `nil` error when compared against `nil` in a normal context.

```go
package baderr

import (
	"testing"

	"gotest.tools/v3/assert"
)

type myEvilError struct{}

func (m *myEvilError) Error() string {
	return "this is an error"
}

func doSomething() error {
	var err *myEvilError
	return err // NOT nil, this has a type.
}

// Should not pass.
func TestErrorNil(t *testing.T) {
	assert.NilError(t, doSomething()) // This says it's nil.
}

func TestErrorNotNil(t *testing.T) {
	assert.Assert(t, doSomething() != nil) // An actual comparison says it's not nil.
}
```

**Comment by dnephin** [comment]
Thanks for the report! I agree the change in #171 was not right. I think the original code did have a problem with it when called with a non-nil error interface with nil value. I'll add these error cases and prepare a fix.

**Comment by zikaeroh** [comment]
Yes, I agree. My only worry with that case however is that a nil valued error is "valid", it's only wrong if its `Error()` method panics. For example, the code given in #167 checked for a nil pointer internally so would be "valid" from an `error` implementation point of view. I would suggest something like the following to safely get the error message for printing:

```go
success := false
message := func() string {
	s := err.Error()
	success = true
	return s
}()

if !success {
	// Report that err was not nil, but Error() panicked.
}

// Report the error message as normal.
```

**Comment by zikaeroh** [comment]
Edited my comment's snippet, forgot to `recover()` which was the whole point, oops...

**Comment by dnephin** [comment]
I think I found a way to handle it and report why the `error` is not nil. Opened #187 with some new test cases
