### ISSUE TITLE
All of the godoc pages appear to be currently blank

### ISSUE THREAD

**Issue by glenjamin** [gotestyourself/gotest.tools#188]
https://godoc.org/gotest.tools/assert is currently showing as blank

although the new site works: https://pkg.go.dev/gotest.tools/assert?tab=doc

<img width="1142" alt="Screenshot 2020-02-06 at 08 35 10" src="https://user-images.githubusercontent.com/151272/73919559-b0c4e780-48bb-11ea-9827-62ffabd9037e.png">

**Comment by vdemeester** [comment]
@glenjamin and the new site also works with the latest version (aka `v3`) : https://pkg.go.dev/gotest.tools/v3/assert?tab=doc

My guess on this is that godoc.org doesn't support go modules as `pkg.go.dev` does. I'm not sure exactly how we can fix it (other than asking upstream for godoc.org to add support for go modules and pray :pray: :stuck_out_tongue_closed_eyes: )

**Comment by dnephin** [comment]
https://groups.google.com/forum/#!msg/golang-dev/mfiPCtJ1BGU/qtCrqlrEEwAJ

godoc is being retired, https://pkg.go.dev is the replacement.

**Comment by glenjamin** [comment]
Does that mean godoc should start breaking already? Or is that purely related to the modules changes?

so far i've found pkg.go.dev to be more clunky and require more clicks, but I see that's called out in their post as something they expect to improve based on feedback

**Comment by dnephin** [comment]
#190 fixes the links in the docs

**Comment by thaJeztah** [comment]
Could we make `http://gotest.tools` redirect to pkg.go.dev ?

**Comment by thaJeztah** [comment]
Hmmm... experience is horrible on `pkg.go.dev`. 

- Going to https://pkg.go.dev/mod/gotest.tools?tab=overview shows the old v2.x documentation. ("v2.2.0+incompatible"), which confusingly shows "latest", but of course is only the "latest" v1/v2 docs
- As a user, I have to consider opening the "versions" tab (https://pkg.go.dev/mod/gotest.tools?tab=versions) to even be aware there's a newer version, and that it's the `v3` package I'm actually looking for https://pkg.go.dev/mod/gotest.tools/v3/?tab=overview

<img width="615" alt="Screenshot 2020-02-18 at 18 07 38" src="https://user-images.githubusercontent.com/1804568/74759806-a7535c00-5279-11ea-965a-f8262b53b5b7.png">

**Comment by dnephin** [comment]
Oh ya! I forgot that is a thing I setup. I can make it redirect to https://pkg.go.dev/gotest.tools/v3/

Adding the `/v3` to the url sends to the right docs

**Comment by thaJeztah** [comment]
Yes, that's probably the best workaround for now.

Won't fix the situation for people that "organically" arrive at the https://pkg.go.dev/gotest.tools "homepage", but at least solves it for some 😞

**Comment by dnephin** [comment]
I [pulled in some changes](https://github.com/gotestyourself/vanityurl/commit/86589d428e16dd3c1c08d7166c51406677cdf94a) which got the https urls to reidrect (https://gotest.tools/), but `http` is still going to the old url for some reason.

I think i should be possible to add a `v3` if there is no version in the url, but I haven't looked at adding that yet.

**Comment by dnephin** [comment]
https://github.com/gotestyourself/vanityurl/pull/2 should fix the "defaults to redirecting to non-v3 urls" problem.

**Comment by glenjamin** [comment]
Would it be possible to publish some pages to https://godoc.org/gotest.tools/assert which simply link to the new location?

I just got caught by this again when using browser history to navigate there.

Or perhaps this is something that godoc.org itself could/should do?

**Comment by marco-m** [comment]
https://godoc.org/gotest.tools/assert redirects to https://pkg.go.dev/gotest.tools/assert?utm_source=godoc, so I think that this issue can be closed.

**Comment by dnephin** [comment]
Ya, things look better now, thanks!
