### ISSUE TITLE
Suite runner

### ISSUE THREAD

**Issue by gchaincl** [gotestyourself/gotest.tools#194]
Is there any plan on implementing a Suite runner like [testify/suite](https://godoc.org/github.com/stretchr/testify/suite)?

**Comment by vdemeester** [comment]
Hey @gchaincl,

There is https://github.com/gotestyourself/gotest.tools/tree/master/x/subtest that "kinda" does that (not the `x` for *experimental*) : https://pkg.go.dev/gotest.tools/v3@v3.0.2/x/subtest?tab=doc

There is no plan to implement Suite I don't think (@dnephin can correct me). We feel the built-in functionnality of `testing` (subtests with `t.Run`, `Cleanup` func) are enough to have something *like a suite*.

**Comment by dnephin** [comment]
The main "feature" of `suite` seems to be that test setup and teardown fixtures are called implicitly based on the struct. I would argue that the standard way of calling them explicitly from each test is a better approach. It makes tests easier to read and maintain when all setup and teardown happens from the test function.

This project was heavily influenced by [pytest](https://docs.pytest.org/en/latest/). One of the original features that made pytest so great in python is that it moved away from the xunit style class setup/teardown, to individual fixtures for every test function.

Are there other features of `testify/suite` that you are interested in?

**Comment by gchaincl** [comment]
Implicit setup and teardown were actually the features I was looking for.
I understand the idea calling setup/teardown functions explicitly on each test, and I like that (I normally do), but there are some tests where haveing them is convinient (think of a large database test suite where you want to allways truncate the tables before each test).
Having a suite package does not force you to use it, but gives you the possibility when you really need it.

**Comment by dnephin** [comment]
One pattern for doing this would be something like this:

```go
func TestDatabase(t *testing.T) {
	var testcases = []struct {
		name string
		run  func(t *testing.T, db *sql.DB)
	}{
		{name: "test insert", run:  testInsert},
		...
	}

	db := newDB()  // equivalent to SuiteSetup
	defer db.Close() // equivalent to SuiteTearDown
	for _, tc := range testcases {
		t.Run(tc.name, func(t *testing.T) {
                        // TestSetup could go here
			defer cleanDB(db) // equivalent to TestTearDown
			tc.run(t, db)
		})
	}
}

func testInsert(t *testing.T, db *sql.DB) {}
```

This pattern has some nice properties: all setup and teardown logic is in one place, and it is pretty standard Go.

**Comment by gchaincl** [comment]
Yeah, that's a nice one, thanks!
