### ISSUE TITLE
Expose golden.flagUpdate with a golden.FlagUpdate method

### ISSUE THREAD

**Issue by odsod** [gotestyourself/gotest.tools#205]
For golden file tests that want to perform custom assertions (for example read proto messages from a golden file and perform a comparison assertion on the parsed message) it would be useful to expose the flagUpdate variable, so that the same flag can be used for all golden file tests (redefining this flag results in a panic).

**Comment by dnephin** [comment]
I think this may be related to #8 in some ways.

One thing I've done to handle this type of problem is this: https://github.com/gotestyourself/gotestsum/blob/master/internal/text/testing.go#L12-L28, you can see it used here: https://github.com/gotestyourself/gotestsum/blob/e2b19e158466ef6e6da12a3c7d0dd0fb825ac740/testjson/dotformat_test.go#L33-L36

By processing the `actual` value you can store it in the golden without needing the read the flag.
