### ISSUE TITLE
golden file trigger unexpected folder creation

### ISSUE THREAD

**Issue by ndeloof** [gotestyourself/gotest.tools#214]
Due to https://github.com/gotestyourself/gotest.tools/blob/main/golden/golden.go#L179
as my golden file is hosted in a subfolder, and even I don't run tests with the `update` flag, I get an attempt to create a folder in current directory
This was detected as I'm using a containerized build with read-only filesystem

**Comment by dnephin** [comment]
Thank you for the bug report! I think #215 should fix it
