### ISSUE TITLE
go 1.18  wrong interface with gotest.tool

### ISSUE THREAD

**Issue by chmouel** [gotestyourself/gotest.tools#225]
Getting this error : 

```
cannot use t (variable of type *testing.T) as “gotest.tools/v3/assert”.TestingT value in argument to env.PatchAll: wrong type for method Log (have func(args ...invalid type), want func(args ...interface{}))
```

**Comment by dnephin** [comment]
Thank you for the bug report! I have just started using go1.18 and it seems to work ok. I'm not sure what's happening here. I'll PR adding go1.18 to CI to start.

**Comment by dnephin** [comment]
The tests seem happy in #227, and I was able to use `env.PatchAll` with go1.18 in a project I am working on.  I haven't been able to reproduce this error yet.

> have func(args ...invalid type)

That part of the error message is surprising. I wonder why it says "invalid type".

**Comment by chmouel** [comment]
@dnephin I looked a bit more into it yesterday and after some fiddling trying to figure out the issue, 

It seems that the issue happen with when using [gopls from homebrew ](https://formulae.brew.sh/formula/gopls), if I switch it with a gopls from `go install golang.org/x/tools/gopls@latest` it doesn't show the error anymore....

they are both using 0.8.1 

I see there is some fix around gopls and generics here https://github.com/golang/go/issues/52015 perhaps it's related?

anywhoo probably not an issue with gotest.tools and this issue may be closed,
