### ISSUE TITLE
fs: more PathOp for matching extra files and content

### ISSUE THREAD

**Issue by dnephin** [gotestyourself/gotest.tools#83]
Right now there is `MatchAnyFileContent`, and `MatchExtraFiles` to match any content and any extra files, but we might want to only allow specific files, or specific content that isn't entirely predictable.

For those cases we could add:

```go

// MatchExtraFilesGlob is a PathOp that updates a Manifest to allow extra files in a directory which
// match the file glob pattern, and with properties that match all ops.
func MatchExtraFilesGlob(glob string, ops ...PathOp) PathOp {
}
```

`MatchFileContent` done in #133 
```go
// MatchFileContent is a PathOp that updates a Manifest to use the provided function to check a files
// content. The function should return true if the content is as expected.
func MatchFileContent(f func([]byte) bool) PathOp {
}
```

**Comment by glefloch** [comment]
Hi, I would like to work on this. Is it possible to contribute to the project?

**Comment by dnephin** [comment]
Hello, yes, contributions are welcome

**Comment by dnephin** [comment]
Done in #133 and #135
