### ISSUE TITLE
fs: Disable mode checking

### ISSUE THREAD

**Issue by sda0** [gotestyourself/gotest.tools#95]
I wanna suggest a feature to disable file/dir mode checks because it may be different environments the app could be run. I cannot be sure that origin directory modes correct or what mode will be in result files manipulations function.

**Comment by sda0** [comment]
yes, such matcher really need.
for example, my func unpacks an archive. Extracted files  on my ubuntu has different modes then on gitlab-agent VM. Also, in other fund I use another utility to unpack and even on my ubuntu it has others modes. now I have to disable file contents checking because of this problem.

**Comment by dnephin** [comment]
Could you provide an example output of the assert when it fails? I'm wondering if these are in the normal `0777` range, or are they other mode flags.

**Comment by dnephin** [comment]
I opened #96, but if you're able to provide the output of the failure I would still like to see it to confirm the defaults are correct.

Thanks!
